name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
      OWNER_ADDRESS: ${{ secrets.OWNER_ADDRESS }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      VITE_PAYER_ADDRESS: ${{ secrets.VITE_PAYER_ADDRESS }}
      VITE_PAYEE_ADDRESS: ${{ secrets.VITE_PAYEE_ADDRESS }}
      VITE_ARBITER_ADDRESS: ${{ secrets.VITE_ARBITER_ADDRESS }}

    services:
      docker:
        image: docker:20.10-dind
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: docker compose up --build -d

      - name: Check running containers
        run: docker ps -a

      - name: Run backend tests
        run: docker compose exec -T backend npm test || true
