name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10-dind
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: docker compose up --build -d

      - name: Check running containers
        run: docker ps -a

      - name: Run backend tests
        run: docker compose exec -T backend npm test || true

      - name: Run frontend build
        run: docker compose exec -T frontend npm run build || true
